"""reservas.placa

Revision ID: 31c22230cfdb
Revises: cd529d7b47c6
Create Date: 2026-09-17 11:27:03.240899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c22230cfdb'
down_revision = 'cd529d7b47c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placa', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_column('placa')

    # ### end Alembic commands ###
