"""ingresos fase2b

Revision ID: 3dc2a6c36035
Revises: ff5efb7207e4
Create Date: 2026-09-16 14:35:16.927294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc2a6c36035'
down_revision = 'ff5efb7207e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_ingreso_salida',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('espacio_id', sa.Uuid(), nullable=False),
    sa.Column('placa', sa.String(length=15), nullable=False),
    sa.Column('operador_id', sa.Uuid(), nullable=True),
    sa.Column('hora_entrada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hora_salida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monto_cobrado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ),
    sa.ForeignKeyConstraint(['operador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_ingreso_salida')
    # ### end Alembic commands ###
