"""mer fase1

Revision ID: 6aa5449680ad
Revises: 
Create Date: 2026-09-15 20:07:16.924965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aa5449680ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'operador', 'cliente', name='user_role', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('zonas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.Enum('cubierto', 'descubierto', 'motos', name='zona_tipo', create_constraint=True), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tarifa_por_hora', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('espacios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zona_id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.Enum('disponible', 'reservado', 'ocupado', 'mantenimiento', name='espacio_estado', create_constraint=True), server_default='disponible', nullable=False),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('bloqueos_mantenimiento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('espacio_id', sa.Uuid(), nullable=False),
    sa.Column('creado_por', sa.Uuid(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bloqueos_mantenimiento')
    op.drop_table('espacios')
    op.drop_table('zonas')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
