"""pagos fase3a

Revision ID: cd529d7b47c6
Revises: 3dc2a6c36035
Create Date: 2026-09-16 15:43:08.276214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd529d7b47c6'
down_revision = '3dc2a6c36035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reserva_id', sa.Uuid(), nullable=True),
    sa.Column('registro_ingreso_id', sa.Uuid(), nullable=True),
    sa.Column('referencia_transaccion', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo', sa.Enum('tarjeta', 'efectivo', name='metodo_pago', create_constraint=True), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'confirmado', 'reembolsado', name='pago_estado', create_constraint=True), server_default='pendiente', nullable=False),
    sa.ForeignKeyConstraint(['registro_ingreso_id'], ['registros_ingreso_salida.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referencia_transaccion'),
    sa.UniqueConstraint('registro_ingreso_id'),
    sa.UniqueConstraint('reserva_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    # ### end Alembic commands ###
