"""reservas fase2a

Revision ID: ff5efb7207e4
Revises: 6aa5449680ad
Create Date: 2026-09-16 13:18:32.339475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5efb7207e4'
down_revision = '6aa5449680ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('espacio_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio_planeada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hora_fin_planeada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('confirmada', 'cancelada', 'completada', name='reserva_estado', create_constraint=True), server_default='confirmada', nullable=False),
    sa.ForeignKeyConstraint(['espacio_id'], ['espacios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    # ### end Alembic commands ###
